name: "Build"

on:
  - push
  - pull_request

jobs:
  build: # Check build on various OSes

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest Windows doesn't work yet
        ocaml-version:
          # Don't include every versions. OCaml-CI already covers that
          - 4.11.1
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      # Clone the project
      - uses: actions/checkout@v2

      # Setup
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam') }}-opam
      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      # Pull the Mdx submodule
      # actions/checkout doesn't support that
      # Also, this is supposed to be temporary
      - run: git submodule update --init

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          # Mdx dependencies
          opam pin add -n ./mdx
          opam depext -y -t mdx
          opam install --deps-only mdx
          # -
          opam pin add -n .
          opam depext -y -t odoc
          opam install --deps-only -t odoc

      - name: dune build
        run: opam exec -- dune build
      - name: dune runtest
        run: opam exec -- dune runtest

  esy: # Check build using esy

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest Not working yet.

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/checkout@v2
      - run: npm --global install esy
      - run: esy install --verbose
      - run: esy odoc --version
