name: "Build"

on:
  - push
  - pull_request

jobs:
  build: # Check build on various OSes

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest Windows doesn't work yet
        ocaml-version:
          # Don't include every versions. OCaml-CI already covers that
          - 4.11.1
        include:
          - os: ubuntu-latest # Enable coverage only on a single build
            send-coverage: true
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      # Clone the project
      - uses: actions/checkout@v2

      # Setup
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam') }}-opam
      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          opam pin add -n .
          opam depext -y -t odoc
          opam install --deps-only -t odoc

      - name: dune build
        run: opam exec -- dune build
      - name: dune runtest
        run: opam exec -- dune runtest

      - name: Send coverage stats to Coveralls
        if: matrix.send-coverage == true
        run: |
          opam exec -- dune runtest --instrument-with bisect_ppx --force
          opam exec -- bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}

  esy: # Check build using esy

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      # Setup
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install esy
        run: npm --global install esy

      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.esy
          key: ${{ matrix.os }}-esy

      - name: Install dependencies # Solve every time (fast)
        run: esy install --verbose

      - name: Build odoc
        run: esy x dune exec src/odoc/bin/main.exe -- --version
